version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      DOMAIN: "${HALO_EXTERNAL_URL}"
    volumes:
      - ./data:/data
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true