version: '3.8'

services:
  dpanel:
    image: dpanel/dpanel:lite
    container_name: ${PANEL_APP_INSTANCE_NAME}
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080"
    environment:
      - APP_NAME=${PANEL_APP_INSTANCE_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/1panel/apps/dpanel-lite/data:/dpanel
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true